spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snap2track
    username: snapuser
    password: snappass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: c2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tbWluLWxlbmd0aC0yNTYtY2hhcnM=
    expiration-ms: 86400000